import type { SmartGraphicCategory, SmartGraphicLayoutId } from '@/lib/smartGraphic';
import type { TranslationKey } from '@/lib/translations';

export const GRAPHIC_CATEGORY_KEYS: Record<SmartGraphicCategory, TranslationKey> = {
  list: 'graphicCategoryList',
  process: 'graphicCategoryProcess',
  timeline: 'graphicCategoryTimeline',
  cycle: 'graphicCategoryCycle',
  hierarchy: 'graphicCategoryHierarchy',
  relationship: 'graphicCategoryRelationship',
  matrix: 'graphicCategoryMatrix',
  pyramid: 'graphicCategoryPyramid',
};

export const GRAPHIC_LAYOUT_KEYS: Record<SmartGraphicLayoutId, TranslationKey> = {
  'list-block': 'graphicLayoutListBlock',
  'list-horizontal': 'graphicLayoutListHorizontal',
  'list-numbered': 'graphicLayoutListNumbered',
  'list-cards': 'graphicLayoutListCards',
  'process-chevron': 'graphicLayoutProcessChevron',
  'process-steps': 'graphicLayoutProcessSteps',
  'process-arrow': 'graphicLayoutProcessArrow',
  'process-staircase': 'graphicLayoutProcessStaircase',
  'timeline-horizontal': 'graphicLayoutTimelineHorizontal',
  'timeline-vertical': 'graphicLayoutTimelineVertical',
  'timeline-alternating': 'graphicLayoutTimelineAlternating',
  'cycle-basic': 'graphicLayoutCycleBasic',
  'cycle-segmented': 'graphicLayoutCycleSegmented',
  'cycle-loop': 'graphicLayoutCycleLoop',
  'hierarchy-org': 'graphicLayoutHierarchyOrg',
  'hierarchy-horizontal': 'graphicLayoutHierarchyHorizontal',
  'hierarchy-tree': 'graphicLayoutHierarchyTree',
  'relationship-opposing': 'graphicLayoutRelationshipOpposing',
  'relationship-radial': 'graphicLayoutRelationshipRadial',
  'relationship-converging': 'graphicLayoutRelationshipConverging',
  'relationship-diverging': 'graphicLayoutRelationshipDiverging',
  'relationship-venn': 'graphicLayoutRelationshipVenn',
  'relationship-nested': 'graphicLayoutRelationshipNested',
  'matrix-grid': 'graphicLayoutMatrixGrid',
  'matrix-swot': 'graphicLayoutMatrixSwot',
  'matrix-titled': 'graphicLayoutMatrixTitled',
  'pyramid-basic': 'graphicLayoutPyramidBasic',
  'pyramid-inverted': 'graphicLayoutPyramidInverted',
  'pyramid-list': 'graphicLayoutPyramidList',
  'pyramid-funnel': 'graphicLayoutPyramidFunnel',
};

/** One-line purpose of each layout, shown in the gallery and used by search. */
export const GRAPHIC_LAYOUT_HINT_KEYS: Record<SmartGraphicLayoutId, TranslationKey> = {
  'list-block': 'graphicLayoutHintListBlock',
  'list-horizontal': 'graphicLayoutHintListHorizontal',
  'list-numbered': 'graphicLayoutHintListNumbered',
  'list-cards': 'graphicLayoutHintListCards',
  'process-chevron': 'graphicLayoutHintProcessChevron',
  'process-steps': 'graphicLayoutHintProcessSteps',
  'process-arrow': 'graphicLayoutHintProcessArrow',
  'process-staircase': 'graphicLayoutHintProcessStaircase',
  'timeline-horizontal': 'graphicLayoutHintTimelineHorizontal',
  'timeline-vertical': 'graphicLayoutHintTimelineVertical',
  'timeline-alternating': 'graphicLayoutHintTimelineAlternating',
  'cycle-basic': 'graphicLayoutHintCycleBasic',
  'cycle-segmented': 'graphicLayoutHintCycleSegmented',
  'cycle-loop': 'graphicLayoutHintCycleLoop',
  'hierarchy-org': 'graphicLayoutHintHierarchyOrg',
  'hierarchy-horizontal': 'graphicLayoutHintHierarchyHorizontal',
  'hierarchy-tree': 'graphicLayoutHintHierarchyTree',
  'relationship-opposing': 'graphicLayoutHintRelationshipOpposing',
  'relationship-radial': 'graphicLayoutHintRelationshipRadial',
  'relationship-converging': 'graphicLayoutHintRelationshipConverging',
  'relationship-diverging': 'graphicLayoutHintRelationshipDiverging',
  'relationship-venn': 'graphicLayoutHintRelationshipVenn',
  'relationship-nested': 'graphicLayoutHintRelationshipNested',
  'matrix-grid': 'graphicLayoutHintMatrixGrid',
  'matrix-swot': 'graphicLayoutHintMatrixSwot',
  'matrix-titled': 'graphicLayoutHintMatrixTitled',
  'pyramid-basic': 'graphicLayoutHintPyramidBasic',
  'pyramid-inverted': 'graphicLayoutHintPyramidInverted',
  'pyramid-list': 'graphicLayoutHintPyramidList',
  'pyramid-funnel': 'graphicLayoutHintPyramidFunnel',
};
